
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
 update_fastlane

default_platform(:ios)

platform :ios do
# 1
#  desc "Create app on Apple Developer and App Store Connect sites"
# 2
#  lane :create_app do
# 3
#​    produce
#  end


 #desc "Take screenshots"
 # lane :screenshot do
 #   snapshot
 # end


 #desc "Create ipa"
  #lane :build do
    # 1
    #enable_automatic_code_signing
    # 2
    #increment_build_number
    # 3
    #gym
  #end
 
 
 
lane :beta do
  #build_app(scheme: "FastYXZLaneUITests")
  #build_app(export_xcargs: "-allowProvisioningUpdates")
  #upload_to_testflight
  upload_to_testflight(skip_waiting_for_build_processing: true)


end



end
